version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "python bot.py"
    tty: true
    stdin_open: true
    volumes:
      - ./src:/usr/src/app
    env_file:
      - .env
